<a href="https://colab.research.google.com/github/SantiagoTaracena01/spam-filter/blob/main/multinomial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task 1.4 (Comparacion de librerias)

#### Se realizara el mismo entreno del conjunto de datos utilizando la libreria de scikit-learn

In [ ]:
# Integrantes: Pedro Arriola (20188), Santiago Taracena (20017), Oscar Lopez (20679), YongBum Park (20117)

# Librerias que se utilizaran

import matplotlib.pyplot as plt
import nltk
import numpy as np
import pandas as pd
import seaborn as sns

# Librerias de Scikit-learn

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, precision_score, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, GaussianNB
from sklearn.utils.multiclass import unique_labels

In [ ]:
# Se abre el archivo txt

data = pd.read_csv('entrenamiento.csv')
data

target                                               text
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5560   spam  This is the 2nd time we have tried 2 contact u...
5561    ham               Will ü b going to esplanade fr home?
5562    ham  Pity, * was in mood for that. So...any other s...
5563    ham  The guy did some bitching but I acted like i'd...
5564    ham                         Rofl. Its true to its name

[5565 rows x 2 columns]

In [ ]:
# Se obtienen los mensajes que son spam y la cantidad

spam = data[data['target'] == 'spam']
spam.count()

target    747
text      747
dtype: int64

In [ ]:
# Se compara dicho valor con los mensajes que son ham

ham = data[data['target'] == 'ham']
ham.count()

target    4818
text      4818
dtype: int64

In [ ]:
data['target'] = np.where(data['target'] == 'spam', 1, 0)
data

target                                               text
0          0  Go until jurong point, crazy.. Available only ...
1          0                      Ok lar... Joking wif u oni...
2          1  Free entry in 2 a wkly comp to win FA Cup fina...
3          0  U dun say so early hor... U c already then say...
4          0  Nah I don't think he goes to usf, he lives aro...
...      ...                                                ...
5560       1  This is the 2nd time we have tried 2 contact u...
5561       0               Will ü b going to esplanade fr home?
5562       0  Pity, * was in mood for that. So...any other s...
5563       0  The guy did some bitching but I acted like i'd...
5564       0                         Rofl. Its true to its name

[5565 rows x 2 columns]

In [ ]:
# Ahora se extrae la cantidad de mensajes por categoria

len_ham = len(data[data['target'] == 0])
len_spam = len(data[data['target'] == 1])

print('Ham: ', len_ham, 'Spam: ', len_spam)

Ham:  4818 Spam:  747


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data['text'],
                                                    data['target'],
                                                    test_size=0.3,
                                                    random_state=1234)

In [ ]:
vectorizer = CountVectorizer(ngram_range=(1, 2)).fit(X_train)
X_train_vectorized = vectorizer.transform(X_train)
X_train_vectorized.toarray().shape

(3895, 38811)

In [ ]:
# Se muestra la vectorizacion de los datos

X_train_vectorized

<3895x38811 sparse matrix of type '<class 'numpy.int64'>'
	with 102545 stored elements in Compressed Sparse Row format>

In [ ]:
# Discretizacion de los datos utilizando Modelo Multinomial NB

multinomial_model = MultinomialNB(alpha=0.1)
multinomial_model.fit(X_train_vectorized, y_train)
predictions = multinomial_model.predict(vectorizer.transform(X_test))
accuracy_score(y_test, predictions)


0.9916167664670659

In [36]:
# Se obtiene la matriz de confusion
confusion_matrix(y_test, predictions)

array([[1438,    7],
       [   7,  218]])

In [ ]:
# Se hacen predicciones para mensajes ham

multinomial_model.predict(vectorizer.transform([
    "Thank you, ABD. Can you also share your Instagram profile?",
    "Hi y'all, We have a Job Openings in the positions of backend engineer.",
    "Dear ABD, it is a plesure to have communication with you regarding the job position."
]))

array([0, 0, 0])

In [ ]:
# Se hacen predicciones para mensajes spam

multinomial_model.predict(vectorizer.transform([
    "congratulations, you have been selected for the one million dollar prize",
    "1-month unlimited calls offer Activate now",
    "Free suscription Call NOW"
]))

array([1, 1, 1])

##### ¿Cuál implementación lo hizo mejor? ¿Su implementación o la de la librería?

##### R// La libreria realizo una mejor prediccion.

##### ¿Por qué cree que se debe esta diferencia?

##### R// La libreria esta diseñada para trabajar con palabras y datos discretos, por lo cual tiene un mejor rendimiento y esta mejor optimizado para este tipo de tareas ya que realiza un mejor manejo de los datos